//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamingService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string OriginalTitle { get; set; }
        public string Description { get; set; }
        public string Director { get; set; }
        public string Cast { get; set; }
        public string Country { get; set; }
        public string ReleaseDate { get; set; }
        public string Dabing { get; set; }
        public string CoverPath { get; set; }
        public string Lenght { get; set; }
    }
}
